name: "DEV development"

concurrency: "1"

on: [push]

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - uses: databricks/setup-cli@main

      - run: databricks bundle deploy
        working-directory: dab
        env:
          DATABRICKS_HOST: https://adb-7405608769552659.19.azuredatabricks.net
          DATABRICKS_TOKEN: ${{secrets.SP_TOKEN}}
          DATABRICKS_BUNDLE_ENV: dev
  
  
  pipeline_update:
    name: "Run pipeline_update"
    runs-on: ubuntu-latest
    environment: dev

    needs:
      - deploy

    steps:
      - uses: actions/checkout@v4

      - uses: databricks/setup-cli@main

      - run: databricks bundle run master_job --refresh-all
        working-directory: dab
        env:
          DATABRICKS_HOST: https://adb-7405608769552659.19.azuredatabricks.net
          DATABRICKS_TOKEN: ${{secrets.SP_TOKEN}}
          DATABRICKS_BUNDLE_ENV: dev